media:
  input: public/assets
  output: /assets
  extensions: 
    - jpg
    - jpeg
    - png
    - gif
    - svg
    - webp

content:
  - name: homepage
    label: Page d'accueil
    type: file
    path: src/content/homepage/index.json
    fields:
      - name: hero
        label: Section Hero
        type: object
        fields:
          - name: title
            label: Titre
            type: object
            fields:
              - name: line1
                label: Ligne 1
                type: string
              - name: line2
                label: Ligne 2
                type: string
              - name: line3
                label: Ligne 3
                type: string
          
          - name: image
            label: Image mascotte
            type: image
          
          - name: badges
            label: Badges
            type: object
            fields:
              - name: badge
                label: Badge
                type: object
                fields:
                  - name: text
                    label: Texte
                    type: string
                  - name: link
                    label: Lien
                    type: string
                  - name: variant
                    label: Variante
                    type: select
                    options:
                      - value: festival
                        label: Festival
                      - value: podcast
                        label: Podcast
                      - value: emission
                        label: Émission
                      - value: appel
                        label: Appel à projets

      - name: stats
        label: Section Statistiques
        type: object
        fields:
          - name: items
            label: Statistiques
            type: object
            fields:
              - name: statItem
                label: Élément Statistique
                type: object
                fields:
                  - name: number
                    label: Nombre
                    type: string
                  - name: label
                    label: Label
                    type: string
                  - name: sublabel
                    label: Sous-label
                    type: string
                  - name: icon
                    label: Icône
                    type: string

      - name: mission
        label: Section Mission
        type: object
        fields:
          - name: title
            label: Titre
            type: string
          - name: description
            label: Description
            type: text
          - name: image
            label: Image de la mission
            type: image
          - name: features
            label: Caractéristiques
            type: object
            fields:
              - name: feature
                label: Caractéristique
                type: object
                fields:
                  - name: text
                    label: Texte
                    type: string
          - name: cta
            label: Appel à l'action
            type: object
            fields:
              - name: text
                label: Texte
                type: string
              - name: link
                label: Lien
                type: string

      - name: featuredContent
        label: Contenu à la Une
        type: object
        fields:
          - name: title
            label: Titre
            type: string
          - name: description
            label: Description
            type: text

      - name: premium
        label: Section Premium
        type: object
        fields:
          - name: heroImage
            label: Image Hero
            type: image
          - name: title
            label: Titre
            type: object
          - name: intro
            label: Introduction
            type: text
          - name: features
            label: Fonctionnalités
            type: object
            fields:
              - name: feature
                label: Fonctionnalité
                type: object
                fields:
                  - name: text
                    label: Texte
                    type: string
          - name: podcastHighlights
            label: Points Forts Podcast
            type: object
            fields:
              - name: podcastHighlight
                label: Point Fort Podcast
                type: object
                fields:
                  - name: title
                    label: Titre
                    type: string
                  - name: description
                    label: Description
                    type: text
                  - name: image
                    label: Image
                    type: image
                  - name: duration
                    label: Durée
                    type: string

      - name: newsletter
        label: Section Newsletter
        type: object
        fields:
          - name: title
            label: Titre
            type: string
          - name: description
            label: Description
            type: text
          - name: placeholder
            label: Placeholder
            type: string
          - name: buttonText
            label: Texte du bouton
            type: string
          - name: badgeText
            label: Texte du badge
            type: string
          - name: socialLinks
            label: Liens Sociaux
            type: object
            fields:
              - name: socialLink
                label: Lien Social
                type: object
                fields:
                  - name: name
                    label: Nom
                    type: string
                  - name: icon
                    label: Icône
                    type: string
                  - name: href
                    label: Lien
                    type: string
                  - name: color
                    label: Couleur
                    type: string
