media:
  input: public/assets
  output: /assets
  extensions: 
    - jpg
    - jpeg
    - png
    - gif
    - svg
    - webp

content:
  - name: homepage
    label: Page d'accueil
    type: file
    path: src/content/homepage/index.json
    fields:
      - name: heroTitle
        label: Titre Hero (Ligne 1)
        type: string

      - name: heroSubtitle
        label: Titre Hero (Ligne 2)
        type: string

      - name: heroTitleEnd
        label: Titre Hero (Ligne 3)
        type: string

      - name: heroImage
        label: Image mascotte
        type: image

      - name: heroBadges
        label: Badges Hero
        type: array
        fields:
          - name: text
            label: Texte
            type: string
          - name: link
            label: Lien
            type: string
          - name: variant
            label: Variante
            type: select
            options:
              - value: festival
                label: Festival
              - value: podcast
                label: Podcast
              - value: emission
                label: Émission
              - value: appel
                label: Appel à projets

      - name: statsItems
        label: Statistiques
        type: array
        fields:
          - name: number
            label: Nombre
            type: string
          - name: label
            label: Label
            type: string
          - name: sublabel
            label: Sous-label
            type: string
          - name: icon
            label: Icône
            type: string

      - name: missionTitle
        label: Titre Mission
        type: string

      - name: missionDescription
        label: Description Mission
        type: text
