collections:
  - label: "Contenu du site"
    folder: "/"
    create: false
    fields:
      - name: hero
        label: "Section Hero"
        widget: object
        fields:
          - { name: "title.line1", label: "Titre Ligne 1", widget: string }
          - { name: "title.line2", label: "Titre Ligne 2", widget: string }
          - { name: "title.line3", label: "Titre Ligne 3", widget: string }
          - { name: "image", label: "Image", widget: image }
          - name: badges
            label: "Badges"
            widget: list
            fields:
              - { name: "text", label: "Texte", widget: string }
              - { name: "link", label: "Lien", widget: string }
              - { name: "variant", label: "Variante", widget: string }
      - name: stats
        label: "Statistiques"
        widget: object
        fields:
          - name: items
            label: "Éléments"
            widget: list
            fields:
              - { name: "number", label: "Nombre", widget: string }
              - { name: "label", label: "Libellé", widget: string }
              - { name: "sublabel", label: "Sous-libellé", widget: string }
              - { name: "icon", label: "Icône", widget: string }
      - name: mission
        label: "Mission"
        widget: object
        fields:
          - { name: "title", label: "Titre", widget: string }
          - { name: "description", label: "Description", widget: text }
          - { name: "image", label: "Image", widget: image }
          - name: features
            label: "Fonctionnalités"
            widget: list
            fields:
              - { name: "text", label: "Texte", widget: string }
          - name: cta
            label: "Appel à l'action"
            widget: object
            fields:
              - { name: "text", label: "Texte", widget: string }
              - { name: "link", label: "Lien", widget: string }
      - name: featuredContent
        label: "Contenu en vedette"
        widget: object
        fields:
          - { name: "title", label: "Titre", widget: string }
          - { name: "description", label: "Description", widget: text }
      - name: premium
        label: "Section Premium"
        widget: object
        fields:
          - { name: "heroImage", label: "Image principale", widget: image }
          - { name: "title", label: "Titre", widget: string }
          - { name: "intro", label: "Introduction", widget: text }
          - name: features
            label: "Fonctionnalités"
            widget: list
            fields:
              - { name: "text", label: "Texte", widget: string }
          - name: podcastHighlights
            label: "Podcasts en vedette"
            widget: list
            fields:
              - { name: "title", label: "Titre", widget: string }
              - { name: "description", label: "Description", widget: text }
              - { name: "image", label: "Image", widget: image }
              - { name: "duration", label: "Durée", widget: string }
      - name: newsletter
        label: "Newsletter"
        widget: object
        fields:
          - { name: "title", label: "Titre", widget: string }
          - { name: "description", label: "Description", widget: text }
          - { name: "placeholder", label: "Placeholder", widget: string }
          - { name: "buttonText", label: "Texte du bouton", widget: string }
          - { name: "badgeText", label: "Texte du badge", widget: string }
          - name: socialLinks
            label: "Liens sociaux"
            widget: list
            fields:
              - { name: "name", label: "Nom", widget: string }
              - { name: "icon", label: "Icône", widget: string }
              - { name: "href", label: "URL", widget: string }
              - { name: "color", label: "Couleur", widget: string }
