media:
  input: public/assets
  output: /assets
  extensions: 
    - jpg
    - jpeg
    - png
    - gif
    - svg
    - webp

content:
  - name: homepage
    label: Page d'accueil
    type: file
    path: src/content/homepage/index.json
    fields:
      - name: title
        label: Titre
        type: string

      - name: description
        label: Description
        type: text

  - name: posts
    label: Posts
    type: collection
    path: src/content/post
    format: mdx
    view:
      fields: [title, published, publishDate]
    fields:
      - name: published
        label: Publié
        type: boolean
        default: false

      - name: publishDate
        label: Date de publication
        type: date

      - name: title
        label: Titre
        type: string

      - name: description
        label: Résumé
        type: text

      - name: category
        label: Type de contenu
        type: select
        options:
          - value: actualite
            label: Actualités
          - value: fiche
            label: Fiches
          - value: live
            label: Lives
          - value: podcast
            label: Podcasts
          - value: tv
            label: Émissions
          - value: premium
            label: Premium

      - name: tags
        label: Mots-clés
        type: string
        list: true

      - name: image
        label: Image de couverture
        type: image

      - name: body
        label: Contenu
        type: rich-text

  - name: site
    label: Paramètres du site
    type: file
    path: src/content/config.ts
    fields:
      - name: title
        label: Titre du site
        type: string

      - name: description
        label: Description du site
        type: text

      - name: url
        label: URL du site
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$

      - name: cover
        label: Image de prévisualisation
        type: image
        description: Image utilisée pour les aperçus sur les réseaux sociaux
